services:
  - type: web
    name: my-node-app
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
